"use client";
import {useEffect,useMemo,useState} from 'react';
import {ResponsiveContainer,PieChart,Pie,Cell,BarChart,Bar,XAxis,YAxis,Tooltip,Legend} from 'recharts';
type Doc={_id:string;[key:string]:any};
type Entity='tasks'|'categories'|'members';
const STATUSES=['TODO','DOING','DONE'];
const COLORS=['#6479ec','#e5a24b','#36b899'];
const blankTask={title:'',description:'',categoryId:'',memberId:'',startDate:'',dueDate:'',completedDate:'',status:'TODO'};
export default function Home(){
 const [page,setPage]=useState('board');const [tasks,setTasks]=useState<Doc[]>([]);const [categories,setCategories]=useState<Doc[]>([]);const [members,setMembers]=useState<Doc[]>([]);
 const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [editing,setEditing]=useState<Doc|null>(null);const [form,setForm]=useState<any>(null);
 async function refresh(){setBusy(true);try{const responses=await Promise.all(['tasks','categories','members'].map(e=>fetch('/api/'+e,{cache:'no-store'})));if(responses.some(r=>!r.ok))throw Error('Cannot load data. Check MongoDB connection.');const [t,c,m]=await Promise.all(responses.map(r=>r.json()));setTasks(t);setCategories(c);setMembers(m);setError('')}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 useEffect(()=>{refresh()},[]);
 async function save(entity:Entity,body:any,id?:string){setBusy(true);try{const response=await fetch(`/api/${entity}${id?'/'+id:''}`,{method:id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const json=await response.json();if(!response.ok)throw Error(json.error||'Save failed');setForm(null);setEditing(null);await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 async function remove(entity:Entity,id:string){if(!confirm('Delete this item?'))return;setBusy(true);try{const r=await fetch(`/api/${entity}/${id}`,{method:'DELETE'});if(!r.ok)throw Error('Delete failed');await refresh()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 function edit(entity:Entity,doc?:Doc){setPage(entity==='tasks'?'board':entity);setEditing(doc||null);setForm({entity,...(doc?{...doc}:entity==='tasks'?blankTask:entity==='categories'?{name:'',color:'#6479ec'}:{name:'',email:'',role:'Member'})})}
 async function move(t:Doc,status:string){await save('tasks',{...t,status,completedDate:status==='DONE'?(t.completedDate||new Date().toISOString().slice(0,10)):''},t._id)}
 const name=(entity:Entity,id:string)=>({categories,members}[entity as 'categories'|'members']||[]).find(x=>x._id===id)?.name||'Unassigned';
 const counts=STATUSES.map(s=>({name:s==='TODO'?'TO DO':s,value:tasks.filter(t=>t.status===s).length}));
 const categoryChart=categories.map(c=>({name:c.name,value:tasks.filter(t=>t.categoryId===c._id).length}));
 const overdue=tasks.filter(t=>t.status!=='DONE'&&t.dueDate&&t.dueDate<new Date().toISOString().slice(0,10)).length;
 const performance=['Early','On Time','Late'].map(label=>({name:label,value:tasks.filter(t=>{if(t.status!=='DONE'||!t.completedDate||!t.dueDate)return false;return label==='Early'?t.completedDate<t.dueDate:label==='On Time'?t.completedDate===t.dueDate:t.completedDate>t.dueDate}).length}));
 return <div className="shell"><aside><div className="brand">▦ <b>KanbanFlow</b></div><div className="subbrand">TASK MANAGEMENT</div>{[['board','▦','Kanban Board'],['dashboard','◫','Dashboard'],['categories','▤','Categories'],['members','♙','Team Members']].map(([key,icon,label])=><button className={'nav '+(page===key?'active':'')} key={key} onClick={()=>{setPage(key);setForm(null)}}>{icon} &nbsp; {label}</button>)}<div className="sidebottom">Next.js + MongoDB<br/>Project 2 • Web Development</div></aside><main><header><div><h1>{({board:'Kanban Board',dashboard:'Dashboard',categories:'Categories',members:'Team Members'} as any)[page]}</h1><p>Manage your team's work in one place.</p></div><button className="refresh" onClick={refresh}>↻ Refresh</button></header>{error&&<div className="error">{error}<button onClick={()=>setError('')}>×</button></div>}
 {page==='board'&&<><div className="toolbar"><span>{tasks.length} tasks in your workspace</span><button className="primary" onClick={()=>edit('tasks')}>+ New Task</button></div><div className="board">{STATUSES.map((s,i)=><section className="column" key={s}><div className="columnhead"><span className={'dot d'+i}></span><b>{s==='TODO'?'TO DO':s}</b><span className="count">{counts[i].value}</span></div>{tasks.filter(t=>t.status===s).map(t=><article className="task" key={t._id}><div className="tasktop"><span className="tag">{name('categories',t.categoryId)}</span><button className="textbtn" onClick={()=>edit('tasks',t)}>Edit</button></div><h3>{t.title}</h3><p>{t.description||'No description'}</p><div className="taskmeta"><span>◷ {t.dueDate||'No due date'}</span><span>♙ {name('members',t.memberId)}</span></div><div className="taskactions"><select aria-label="Move task" value={t.status} onChange={e=>move(t,e.target.value)}>{STATUSES.map(s=><option key={s} value={s}>{s}</option>)}</select><button className="danger" onClick={()=>remove('tasks',t._id)}>Delete</button></div></article>)}{!counts[i].value&&<div className="empty">No tasks yet</div>}</section>)}</div></>}
 {page==='dashboard'&&<><div className="stats">{[['Total Tasks',tasks.length],['To Do',counts[0].value],['Doing',counts[1].value],['Done',counts[2].value],['Overdue',overdue]].map(([label,value])=><div className="stat" key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><div className="charts"><div className="panel"><h3>Task Status</h3><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={counts} dataKey="value" nameKey="name" innerRadius={62} outerRadius={92}>{counts.map((_,i)=><Cell key={i} fill={COLORS[i]}/>)}</Pie><Tooltip/><Legend/></PieChart></ResponsiveContainer></div><div className="panel"><h3>Tasks by Category</h3><ResponsiveContainer width="100%" height={260}><BarChart data={categoryChart}><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" fill="#6479ec" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div><div className="panel"><h3>Completion Performance</h3><ResponsiveContainer width="100%" height={260}><BarChart data={performance}><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="value" fill="#36b899" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></div></>}
 {(page==='categories'||page==='members')&&<><div className="toolbar"><span>Manage {page} for task assignments</span><button className="primary" onClick={()=>edit(page as Entity)}>+ Add {page==='categories'?'Category':'Member'}</button></div><div className="panel"><table><thead><tr><th>Name</th><th>{page==='categories'?'Color':'Email'}</th><th>{page==='categories'?'':'Role'}</th><th>Actions</th></tr></thead><tbody>{(page==='categories'?categories:members).map(d=><tr key={d._id}><td><b>{d.name}</b></td><td>{page==='categories'?<span className="swatch" style={{background:d.color||'#6479ec'}}/>:d.email}</td><td>{d.role||''}</td><td><button className="textbtn" onClick={()=>edit(page as Entity,d)}>Edit</button><button className="danger" onClick={()=>remove(page as Entity,d._id)}>Delete</button></td></tr>)}</tbody></table>{!(page==='categories'?categories:members).length&&<p className="empty">Nothing here yet. Add your first item.</p>}</div></>}
 {form&&<div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)setForm(null)}}><form className="modal" onSubmit={e=>{e.preventDefault();const {entity,_id,...body}=form;save(entity,body,_id)}}><div className="modalhead"><h2>{editing?'Edit':'Create'} {form.entity==='tasks'?'Task':form.entity==='categories'?'Category':'Member'}</h2><button type="button" onClick={()=>setForm(null)}>×</button></div><div className="fields">{form.entity==='tasks'?<><label>Title<input required value={form.title||''} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Description<textarea value={form.description||''} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="twocol"><label>Category<select value={form.categoryId||''} onChange={e=>setForm({...form,categoryId:e.target.value})}><option value="">Unassigned</option>{categories.map(c=><option key={c._id} value={c._id}>{c.name}</option>)}</select></label><label>Responsible Person<select value={form.memberId||''} onChange={e=>setForm({...form,memberId:e.target.value})}><option value="">Unassigned</option>{members.map(m=><option key={m._id} value={m._id}>{m.name}</option>)}</select></label><label>Start Date<input type="date" value={form.startDate||''} onChange={e=>setForm({...form,startDate:e.target.value})}/></label><label>Due Date<input type="date" value={form.dueDate||''} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value,completedDate:e.target.value==='DONE'?(form.completedDate||new Date().toISOString().slice(0,10)):''})}>{STATUSES.map(s=><option key={s}>{s}</option>)}</select></label><label>Completed Date<input type="date" value={form.completedDate||''} onChange={e=>setForm({...form,completedDate:e.target.value})}/></label></div></>:form.entity==='categories'?<><label>Category Name<input required value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Color<input type="color" value={form.color||'#6479ec'} onChange={e=>setForm({...form,color:e.target.value})}/></label></>:<><label>Member Name<input required value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input type="email" value={form.email||''} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Role<input value={form.role||''} onChange={e=>setForm({...form,role:e.target.value})}/></label></>}</div><div className="modalfoot"><button type="button" onClick={()=>setForm(null)}>Cancel</button><button className="primary" disabled={busy} type="submit">{busy?'Saving...':'Save Changes'}</button></div></form></div>}
 </main></div>
}
